### ISSUE TITLE
Cache issue-.net core 3.0-Could not load type 'System.Web.Caching.CacheItemPriority' 

### ISSUE THREAD

**Issue by nambir** [nhibernate/NHibernate-Caches#78] opened 2019-12-20 13:10 UTC
I was using nhibernate for Cache in old .net framework.

Now we are rewriting to .net core 3.0.

We are having runtime issue for nhibernate cache.

Inner Exception
Could not load type 'System.Web.Caching.CacheItemPriority' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.":"System.Web.Caching.CacheItemPriority

Exception:
{"An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.\r\n\r\n
![nhibernate cache issue](https://user-images.githubusercontent.com/16057911/71256889-30bcdf80-2358-11ea-836c-ff7c6b1f63ae.jpg)

**Comment by hazzik** [comment] 2019-12-20 21:38
Duplicate of #77

**Closed by hazzik** 2019-12-20 21:38 UTC
